server:
  port: 7000
eureka:
  instance:
    hostname: localhost
  client:
    #默认设置下，该服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为
    #表示是否将自己注册到 Eureka Server，默认为 true。
    register-with-eureka: false
    #表示是否从 Eureka Server 获取注册信息，默认为 true。
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka-server
  cloud:
    # 配置中心的设置
    config:
      server:
        git:
          uri: https://github.com/a464570362/spring-clound-config.git # 配置git仓库的地址
          #search-paths: config-repo # git仓库地址下的相对地址，可以配置多个，用,分
          username: jayzhouls
          password: shuai515515github